title: Eron Visual Studio
description: NAVERON blogs
theme: just-the-docs

# logo: "https://avatars.githubusercontent.com/u/14134183?v=4"
url: https://naveron.github.io/

aux_links:
  NAVERON GITHUB: https://github.com/NAVERON/naveron.github.io
aux_links_new_tab: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.4.0"

color_scheme: dark


# For copy button on code blocks
enable_copy_code_button: true




