title: 玉龙视效工作室
description: 玉龙个人网站博客聚集地
theme: just-the-docs
# logo: "https://avatars.githubusercontent.com/u/14134183?v=4"
favicon_ico: "/favicon.ico"

url: https://naveron.github.io/

aux_links:
  ERON GITHUB: https://github.com/NAVERON
aux_links_new_tab: true

nav_external_links:
  - title: evs on github
    url: "https://github.com/NAVERON/naveron.github.io"
    hide_icon: false
    opens_in_new_tab: true
  - title: evs on bilibili
    url: "https://space.bilibili.com/89060131"
    hilde_icon: false
    opens_in_new_tab: true

# set back to top
back_to_top: true
back_to_top_text: "Back To Top"

color_scheme: dark

# Version of mermaid library
mermaid:
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.5.1"

# math: mathjax

# For copy button on code blocks
enable_copy_code_button: true

# callout configs
callouts:
  admonition:
    # title:
    color: grey-lt
  attention:
    title: Attention
    color: purple
  caution:
    title: Caution
    color: yellow
  danger:
    title: Danger
    color: red
  error:
    title: Error
    color: red
  highlight:
    color: yellow
    opacity: 0.5
  hint:
    title: Hint
    color: grey-dk
  important:
    title: Important
    color: green
  note:
    title: Note
    color: blue
    # color: pink
    opacity: 0.3
  tip:
    title: Tip
    color: grey-dk
  warning:
    title: Warning
    color: red

exclude:
 # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
 # specific to the theme website:
   - bin/
   - lib/
   - "*.gemspec"
   - "*.gem"
   - LICENSE.txt
   - package.json
   - package-lock.json
   - Rakefile
   - README.md
   - CODE_OF_CONDUCT.md
   - docker-compose.yml
   - Dockerfile


# plugins:
#  - xxx





