title: 玉龙视效工作室
description: 玉龙个人网站博客聚集地
theme: just-the-docs
# logo: "https://avatars.githubusercontent.com/u/14134183?v=4"
url: https://naveron.github.io/

aux_links:
  NAVERON GITHUB: https://github.com/NAVERON
aux_links_new_tab: true

nav_external_links:
  - title: evs on github
    url: "https://github.com/NAVERON/naveron.github.io"
    hide_icon: false
    opens_in_new_tab: true

color_scheme: dark

# Version of mermaid library
mermaid:
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.4.0"

# math: mathjax

# For copy button on code blocks
enable_copy_code_button: true

# callout configs
callouts:
  admonition:
    # title:
    color: grey-lt
  attention:
    title: Attention
    color: purple
  caution:
    title: Caution
    color: yellow
  danger:
    title: Danger
    color: red
  error:
    title: Error
    color: red
  highlight:
    color: yellow
    opacity: 0.5
  hint:
    title: Hint
    color: grey-dk
  important:
    title: Important
    color: green
  note:
    title: Note
    color: blue
    # color: pink
    opacity: 0.3
  tip:
    title: Tip
    color: grey-dk
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-seo-tag
  - jekyll-include-cache





